"""empty message

Revision ID: e468e288145d
Revises: 
Create Date: 2023-09-21 18:16:48.698040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e468e288145d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'time_modify',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'time_modify',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
